# Generated by Django 3.1.2 on 2020-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_checkbox'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckBox',
        ),
        migrations.AddField(
            model_name='topic',
            name='choices',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
