# Generated by Django 3.1.2 on 2020-11-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20201109_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='receiver',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
