# Generated by Django 3.1.2 on 2020-11-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_topic_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='choices',
            field=models.CharField(max_length=8),
        ),
    ]
