# Generated by Django 3.1.2 on 2020-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0009_auto_20201109_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='choices',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=100),
        ),
    ]
