# Generated by Django 3.1.2 on 2020-11-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='choices',
        ),
    ]
