# Generated by Django 3.1.2 on 2020-11-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_remove_topic_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='receiver',
        ),
    ]
